version: '3'

# Run this file with something like:
# docker-compose --project-name=cen_tos up --remove-orphans

services:

    memcached: # to connect use: docker exec -it centos-memcached bash
        container_name: 'centos-memcached'
        image: 'khalifahks/centos-memcached'
        networks:
            webEnvNet:
                aliases: # assigns a hostname to the container.
                    - 'wen_memcached'
        ports:
            - '11211:11211'

    nginx: # to connect use: docker exec -it centos-nginx bash
        container_name: 'centos-nginx'
        image: 'khalifahks/centos-nginx'
        depends_on:
            - 'apps' # Because NginX configs will be point to this container.
            - 'apps54' # Because NginX configs will be point to this container.
        networks:
            webEnvNet:
                aliases:
                    - 'wen_nginx'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - "${NGINX_CONFS_DIR}:/etc/nginx/conf.d"
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_CONFIG_IP}"

    # mysql: # to connect use: docker exec -it centos-mysql bash
    #     container_name: 'centos-mysql'
    #     image: 'khalifahks/centos-mysql'
    #     networks:
    #         webEnvNet:
    #             aliases:
    #                 - 'wen_mysql'
    #     volumes:
    #         - "${APPS_DIR}/mysql:/var/lib/mysql"

    # This is the docker container to login to and build your apps.
    apps: # to connect use: docker exec -it centos-apps bash
        container_name: 'centos-apps'
        image: 'khalifahks/centos-apps'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_apps'
        volumes:
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"
        ports:
            - '9000:9000'
            - '10000:1000'
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_CONFIG_IP}"

    # This is the docker container to login to and build your apps.
    apps54: # to connect use: docker exec -it centos-apps bash
        container_name: 'centos-apps54'
        image: 'khalifahks/centos-apps:54'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_apps54'
        volumes:
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"

networks:
    webEnvNet: