version: '2'

services:
    memcached: # to connect use: docker exec -it centos-memcached bash
        container_name: 'centos-memcached'
        image: 'khalifahks/centos-memcached'
        networks:
            webEnvNet:
                aliases: # assigns a hostname to the container.
                    - 'wen_memcached'
        ports:
            - '11211:11211'

    nginx: # to connect use: docker exec -it centos-nginx bash
        container_name: 'centos-nginx'
        image: 'khalifahks/centos-nginx'
        depends_on:
            - 'php'
            - 'php54'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_nginx'
        ports:
            - '8081:80'
            - '3443:443'
        volumes:
            - "${NGINX_CONFS_DIR}:/etc/nginx/conf.d"
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"

    php: # to connect use: docker exec -it centos-php bash
        container_name: 'centos-php'
        image: 'khalifahks/centos-php'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_php'
        volumes:
            # The directory should also map to the same directory where Nginx
            # serves up PHP files.
            # So the "root" directive in an Ngixn configuration server block
            # should start with this as well.
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"

    php54: # to connect use: docker exec -it centos-php54 bash
        container_name: 'centos-php54'
        image: 'khalifahks/centos-php:54'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_php54'
        volumes:
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"

    mysql: # to connect use: docker exec -it centos-mysql bash
        container_name: 'centos-mysql'
        image: 'khalifahks/centos-mysql'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_mysql'
        volumes:
            - "${APPS_DIR}/mysql:/var/lib/mysql"

    # This is the docker container to login to and build your apps.
    apps: # to connect use: docker exec -it centos-apps bash
        container_name: 'centos-apps'
        image: 'khalifahks/centos-apps'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_apps'
        volumes:
            - "${NGINX_CONFS_DIR}:/etc/nginx/conf.d"
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"

    # This is the docker container to login to and build your apps.
    apps54: # to connect use: docker exec -it centos-apps bash
        container_name: 'centos-apps54'
        image: 'khalifahks/centos-apps:54'
        networks:
            webEnvNet:
                aliases:
                    - 'wen_apps54'
        volumes:
            - "${NGINX_CONFS_DIR}:/etc/nginx/conf.d"
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"
networks:
    webEnvNet: